-- +postgres
CREATE TABLE IF NOT EXISTS heart_rate (
  id SERIAL PRIMARY KEY,
  bpm SMALLINT NOT NULL,
  time TIMESTAMP NOT NULL UNIQUE,
  rr_intervals TEXT NOT NULL
);

-- +sqlite
CREATE TABLE IF NOT EXISTS heart_rate (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bpm SMALLINT NOT NULL,
  time DATETIME NOT NULL UNIQUE,
  rr_intervals TEXT NOT NULL
);
