-- +postgres
CREATE TABLE IF NOT EXISTS sleep_cycles (
  id UUID PRIMARY KEY,
  sleep_id DATE NOT NULL UNIQUE,
  start TIMESTAMP NOT NULL,
  end TIMESTAMP NOT NULL,
  min_bpm SMALLINT NOT NULL,
  max_bpm SMALLINT NOT NULL,
  avg_bpm SMALLINT NOT NULL,
  min_hrv INTEGER NOT NULL,
  max_hrv INTEGER NOT NULL,
  avg_hrv INTEGER NOT NULL
);

-- +sqlite
CREATE TABLE IF NOT EXISTS sleep_cycles (
  id TEXT PRIMARY KEY,
  sleep_id DATE NOT NULL UNIQUE,
  start DATETIME NOT NULL,
  end DATETIME NOT NULL,
  min_bpm SMALLINT NOT NULL,
  max_bpm SMALLINT NOT NULL,
  avg_bpm SMALLINT NOT NULL,
  min_hrv INTEGER NOT NULL,
  max_hrv INTEGER NOT NULL,
  avg_hrv INTEGER NOT NULL
);
