-- +postgres
ALTER TABLE heart_rate ADD COLUMN IF NOT EXISTS synced BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sleep_cycles ADD COLUMN IF NOT EXISTS synced BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS synced BOOLEAN NOT NULL DEFAULT FALSE;

-- +sqlite
ALTER TABLE heart_rate ADD COLUMN synced BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sleep_cycles ADD COLUMN synced BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE activities ADD COLUMN synced BOOLEAN NOT NULL DEFAULT FALSE;
